export const meta = {
  name: 'gang-life-wave3',
  description: 'Round-3 feedback: witness-gated wanted, no-shoot-through-walls, aircraft+missiles, NPC reactivity, signs-on-store, doors, bodies, carjack, dumb-text, whoosh',
  phases: [{ title: 'Build' }],
}

const ROOT = '/Users/elifoltyn/Downloads/game'

const base = [
  'CELL BLOCK Z / "Gang Life" at ' + ROOT + ': a no-build Three.js r128 browser game, vanilla JS, ~140 IIFE modules on window.CBZ, booted by ordered <script> tags in index.html. Focus = CITY mode (g.mode==="city"), a GTA-style open world. Per-frame work registers via CBZ.onUpdate(order,fn) (plays-only) or CBZ.onAlways(order,fn); gate every hook with: if (CBZ.game.mode!=="city") return;.',
  '',
  'OWNER DIRECTIVE (read the spirit): the city feels like a GHOST WORLD with dumb pointless AI; only cops react intelligently; lots of half-built ghost code and weak realism. GTA is a REFERENCE, NOT a clone — make every detail RELEVANT to OUR game. Be ambitious, fill in real detail, do not leave stubs.',
  '',
  'HARD RULES:',
  '- ONLY edit the file(s) assigned to you. index.html and src/config.js are OFF LIMITS (lazy-init new state as g.x = g.x || ...). Editing another file corrupts a parallel agent and breaks the build.',
  '- This is a LIVE working game: PRESERVE existing behavior and every public CBZ.* function you find; extend SURGICALLY, do not rewrite whole files. Match the surrounding code style.',
  '- After EVERY edit run `node --check <file>` and FIX any error before you finish. Your file MUST parse or the whole game dies.',
  '- Keep it CHEAP (runs on phones): shared geometry/material, time-slicing, distance LOD, pooling, capped counts. No per-frame allocations in hot loops.',
  '- Where design guidance helps, do 1-2 quick WebSearches (e.g. "GTA <topic>") and steal concrete ideas/numbers, THEN implement. Do not over-research — ship code.',
  '- End with a 3-4 sentence PLAIN-TEXT summary of what you changed + confirm node --check passed. (Your final text is the return value, not a message to a human.)',
  '',
  'KEY CONTRACTS: CBZ.game(=g){cash,cityBank,respect,wanted,heat,cityKills,cityWeapon,cityInv,cityCrew,playerGang,cityMasked,mode,state}. CBZ.player.pos(.x/.y/.z)/.driving/.hp/.maxHp/.stamina/._armor/._vehicle. CBZ.city.note(msg,secs)/.big(msg)/.addCash(n)/.addRespect(n)/.addKill(). CBZ.cityHudDirty(). CBZ.cityPeds[] ped{pos,name,kind,aggr,hp,maxHp,dead,deadT,ko,state,target,finalGoal,path,rage,fear,guard,companion,recruited,armed,weapon,ammo,archetype,wealth,gang,rank,group,char,mem,witnessSev,witnessType,alarmed}. CBZ.cityCops[]. CBZ.cityCars[] car{pos,v,heading,player,npcDriver,stolen,group,color,userData.body,userData.cabin,crumple,wreckT,baseV,driver}. CBZ.cityGangs[]. CBZ.city.playerActor (the player as a "who" for memory/blame). CBZ.city.arena{shopLots,lots,abandonedLots,homeLots,randomSidewalkPoint(),nearestIntersection(),clampToCity(pos,r),root}. lot{cx,cz,w,d,kind,building{name,door{x,z,nx,nz},shop,kind,owned,gang}}. CBZ.cityEcon{ITEMS,SHOP_STOCK,CARS,buyPrice,sellPrice,streetPrice,recordSale,rollCash,propIndex}. CBZ.cityCrime(amt,{x,z,type}). CBZ.cityReport(sev,{x,z,type}). CBZ.cityTagWitnesses(x,z,sev,type). CBZ.collide(pos,r,y0,y1). CBZ.colliders[]{minX,maxX,minZ,maxZ,ref,[y0,y1]}. CBZ.losBlockers[] (meshes that block sight/shots). CBZ.shake(m)/doHitstop(s)/doSlowmo(s). CBZ.gore(x,y,z,{dir,amount,player}). CBZ.body{hit(a,opts),knockdown(a,opts),fling(a,opts),busy(a)} (ragdoll). CBZ.cityExplosion(x,z,{power,radius,byPlayer}). CBZ.cityCrowdRayHit/cityCrowdKill/cityCrowdCircleKill (ambient instanced crowd). CBZ.tracer/muzzleFlash. CBZ.makeLabelSprite(text). CBZ.sfx(name) — REAL recorded m4a ONLY; existing names: shoot_pistol/smg/carbine/shotgun, punch, hit, ko, headshot, whoosh, step, glass, explosion, coin, siren, win, door. Do NOT invent audio names unless YOUR job is to add a real sample to the bank.',
  '',
  'SHARED HELPER (provided): CBZ.clearLineOfFire(ax,ay,az,bx,by,bz) -> true if there is a CLEAR shot between two world points (nothing in CBZ.losBlockers between them). Call it BEFORE any NPC/cop fires so they stop shooting through walls.',
  '',
  'FREE KEYS (everything else is taken): only a handful remain — prefer reusing existing menus/interactions over new global keys. Taken: WASD I J K L E F C V M B U G T N O Tab Y Z H Q R P X.',
].join('\n')

const DOMAINS = [

  { key: 'peds-ai', files: 'src/city/peds.js', task:
    'Make NPC AI SMART + ALIVE so the city is not a ghost world, in peds.js (the time-sliced city ped brain think/move). FOUR things:\n' +
    '(1) UNIVERSAL REACTIVITY — right now only cops act smart. Make ANY ped pick a believable reaction to the player based on personality (aggr, archetype, wealth, gang, fear) + context (your wanted level, whether your gun is OUT, your respect, whether you just hit/robbed them or someone near them): on a spectrum they should be able to — try to KILL you (armed/aggressive), FLEE screaming, TRADE/offer a deal, try to STEAL from you or pickpocket, ask to WORK for you, BEAT you up (fists), IGNORE you, or just TALK / ask a favor. Make it emergent and varied, not random spam. Coexist with the aigoals.js goal hooks (it sets ped.finalGoal/target/rage for make-money/get-drugs/survive routines) and the existing interact.js options.\n' +
    '(2) WITNESS REPORTING (the player only gets WANTED when a crime is REPORTED to real police — never instantly). You OWN the witness DECISION + behavior. The seam: wanted.js calls CBZ.cityTagWitnesses(x,z,sev,type) when the player commits a crime; that tags nearby peds with witnessSev/witnessType/mem=playerActor. A tagged ped then DECIDES whether to snitch, scaled by: NEIGHBORHOOD (on gang turf / "the hood" almost nobody calls the cops — no-snitch code + they hate police too; in a clean/rich area someone calls fast), a per-ped SNITCH trait (roll a rare ped.snitch at spawn — a snitch rats anywhere, fast; gang members keep omerta unless ratting a RIVAL), and fear/personality. A ped that decides to report does ONE of: pull out a PHONE and call (a timer, show a visible phone tell over them) OR physically RUN to the nearest cop and report on arrival (a running tell). ONLY when that completes do they call CBZ.cityReport(witnessSev,{x,z,type:witnessType}). Some instead pull a gun on the player or just flee. The player must be able to STOP the report by killing/scaring the reporter before it lands. A cop who DIRECTLY sees the crime still reports immediately (cops are always reporting authorities).\n' +
    '(3) WALL AVOIDANCE — idiot peds keep walking into walls. Add real look-ahead avoidance + separation (build on the existing _stuck reroute): probe a short ray/AABB ahead via CBZ.colliders and steer around before grinding the wall.\n' +
    '(4) WHOOSH BUG — the repetitive whoosh in the city is THIS file: the crowd-panic line (~219) and the fearful-scream line (~753) play CBZ.sfx("whoosh") as a DIY scream. Replace BOTH with a real CBZ.sfx("scream") (a real "scream" sample is being added to the audio bank in parallel; wrap the call so a missing sample is harmless), and DROP the frequency hard — a scream should be RARE per ped with a multi-second cooldown, not every panic frame. Never use "whoosh" for screams.\n' +
    'PRESERVE: companionThink (bodyguard/gang follower brain), the _stuck detection, npcAttack, cityTagWitnesses signature, and the aigoals hooks. peds.js is LARGE and central — be surgical, additive, node --check after every edit.' },

  { key: 'wanted', files: 'src/city/wanted.js', task:
    'Make WANTED witness-gated in wanted.js (RDR2 logic): committing a crime must NOT raise stars instantly — it only flags witnesses; stars rise ONLY when a witness report actually REACHES police. SPECIFICS:\n' +
    '- cityCrime(amount,{x,z,type}) (the act): do NOT raise stars by itself. It should call CBZ.cityTagWitnesses(x,z,amount,type) to mark nearby peds as witnesses, and if a COP directly sees it (cop within sight/range) report immediately. That is the only "instant" path.\n' +
    '- cityReport(sev,{x,z,type}) (called by peds.js when a witness finishes calling/reaching a cop): THIS is the only thing that raises stars. Apply the RDR2 crime->star tiers already in this file (assault 1, shots-fired/GTA/robbery/vehicular 2, murder 3, multi-murder 4, terrorism/cop-killer 5). Honor g.cityMasked (shiesty/bandana = unidentified, no stars). Keep crime NAMES.\n' +
    '- Make sure nothing ELSE in this file bumps g.wanted/g.heat directly off a raw action. Keep the decay, the masked toggle, cityWantedReset, and all existing exports (cityCrime, cityReport). cityTagWitnesses is OWNED by peds.js — do not redefine it here, just call it.\n' +
    'This coordinates with the peds-ai agent across the cityTagWitnesses -> cityReport seam; keep those signatures EXACTLY. Research GTA/RDR2 wanted/witness design briefly, then implement. node --check.' },

  { key: 'police', files: 'src/city/police.js', task:
    'GTA-grade POLICE in police.js. THREE things:\n' +
    '(1) GUN STOP — when the player is openly carrying a gun (g.cityWeapon is a firearm / weapon drawn) but is NOT yet wanted, a nearby cop should approach and CHALLENGE them about the weapon. Present interaction options that are EXCUSES + COMPLY + EXECUTE: e.g. "It is licensed" / "Just heading to the range" (talk your way out — success scales with the cop suspicion + your respect), COMPLY (holster/put it away, cop backs off), or EXECUTE (draw and shoot the cop — instant heat). Reuse the existing city interaction/menu plumbing (interact.js style) rather than a new global key.\n' +
    '(2) NO SHOOTING THROUGH WALLS — cops must call CBZ.clearLineOfFire(muzzle..., target...) before firing and NOT shoot when a building blocks the shot; instead reposition/flank to get a real angle, and hide/lower the gun prop when there is no line of sight (fixes guns poking through walls).\n' +
    '(3) SMARTER PURSUIT — flank, use cover, and when the player breaks line of sight, switch to SEARCH/give-up rather than wallhacking. Keep the wanted-tier escalation; the actual helicopter + jets live in city/aircraft.js (a parallel agent) — keep whatever spawn hooks it needs but do not build the aircraft here.\n' +
    'PRESERVE existing cop spawn/hurt/arrest APIs + the wanted.js integration. Research GTA wanted/police pursuit briefly. node --check.' },

  { key: 'aircraft', files: 'src/city/aircraft.js', task:
    'BUILD police AIR support in aircraft.js (currently a stub — fill it). It is an IIFE with its own CBZ.onUpdate(order, fn) gated to city mode. FEATURES:\n' +
    '- A pursuit HELICOPTER that spawns at high wanted (>=4 stars): a low-poly heli with spinning rotor + a SPOTLIGHT cone that tracks the player, circling overhead. Spawn it from a rooftop HELIPAD if CBZ.cityHelipad() exists (buildings agent provides {x,y,z}); otherwise fly it in from the map edge.\n' +
    '- At 5 STARS: the heli fires MISSILES at the player on a cooldown, and FIGHTER JETS scream across and strafe with missiles. A missile travels (visible projectile + smoke trail) and on impact triggers a BIG explosion: call CBZ.cityAirstrikeExplosion(x,z,{power,radius,byPlayer:false}) if it exists (crashfx agent adds it — bigger/longer than a car blast), else fall back to CBZ.cityExplosion(x,z,{power:2.2,radius:11}). On a building hit, also call CBZ.cityDamageBuilding(x,y,z,power) if it exists (buildings agent adds it) for cinematic structural damage. Missiles should hurt the player + crowd in radius (the explosion already handles blast damage).\n' +
    '- Keep it CHEAP and gated strictly to high wanted; despawn when wanted drops/clears. Pool projectiles. Feature-detect every cross-module hook so missing ones degrade gracefully.\n' +
    'Lazy-init any g.* state. Research GTA attack-helicopter / jet behavior briefly. node --check.' },

  { key: 'explosions', files: 'src/city/crashfx.js', task:
    'In crashfx.js: (1) make crash explosions + their FIRE LAST LONGER (owner: blasts/fires after crashes are good but too brief) — extend the fireball/smoke/flame lifetimes and the burning-wreck duration noticeably. (2) ADD a reusable CBZ.cityAirstrikeExplosion(x,z,{power,radius,byPlayer}) — a BIGGER, LONGER variant of cityExplosion for missiles/airstrikes: a larger expanding white-hot->orange->deep-red fireball, a taller/longer-lingering black smoke COLUMN, more debris + sparks, a stronger shake + a touch of slow-mo, scorch. It must reuse the same blast-damage path cityExplosion uses (cityCrowdCircleKill / cityKillPed / cityHurtCop / cityHurtPlayer) so it actually damages people. (3) keep crash impact VFX (sparks/glass/debris) intact. PRESERVE the cityExplosion(x,z,opts) signature + cityCrashFX + the pooled sprite system. Keep it pooled/cheap. node --check.' },

  { key: 'buildings', files: 'src/city/buildings.js', task:
    'In buildings.js, FOUR things: (1) STORE SIGNS GO ON THE STORE — make each storefront sign prominent + readable mounted ON the facade above the door / on the wall (use the per-business name + sign color + a CBZ.makeLabelSprite), so the building announces itself WITHOUT any freestanding sidewalk sign. (2) OPENABLE DOORS — store doors are currently solid "walls that do not move". Make the door panel actually OPEN (swing or slide, animated) when the player is close / entering, and be PASSABLE while open (do not leave a collider blocking the doorway); close behind. (3) BUILDING DAMAGE — expose CBZ.cityDamageBuilding(x,y,z,power): at a hit point, knock off debris CHUNKS, add a scorch/impact decal, and break nearby windows — cinematic structural damage for missiles/explosions (called by the aircraft + explosions agents). Keep pooled + capped. (4) HELIPAD — put a flat rooftop HELIPAD (a marked pad with an H) on one tall building and expose CBZ.cityHelipad() returning its {x,y,z} (used by the aircraft agent). PRESERVE the interiors (furnishInterior), windows, platforms, colliders, and bullet-hole decals. Research GTA storefront/destruction briefly. node --check.' },

  { key: 'exterior', files: 'src/city/props.js, src/city/world.js', task:
    'In props.js (+ world.js only if needed): (1) KILL the freestanding A-FRAME sidewalk STORE signs (aFrameSign / its placement near shop doors) — signs belong ON the store now (buildings agent handles the facade). You may keep a sparse few generic ones but remove the per-shop sidewalk signs. (2) BILLBOARDS + ad panels currently show DUMB GENERIC/"GPT" filler — replace the ad/slogan content pool with RELEVANT IN-WORLD content: the city gangs + their colors, real in-game shops (Ammu-Nation, Bling Jewelers, etc.), the player notoriety/wanted, mock local brands + radio stations + funny in-world ads, and the occasional WANTED poster. Make it feel like OUR city, not a clone. (3) keep the good decor (lamp posts, hydrants, planters, etc.). PRESERVE the traffic-light system + the streetProps/billboard render loop. node --check.' },

  { key: 'bodies', files: 'src/city/crowd.js, src/systems/grapple.js', task:
    'BODIES + crowd spawn. In crowd.js: (1) corpses must rest FULLY ON the ground — fix the lying-flat render so bodies do not sink partway underground (raise the lying Y so the body lies ON the surface). (2) bodies STAY LONGER — raise the corpse linger (corpseT) from ~7s to ~25-30s before they fade. (3) crowd SPAWN/PROMOTION must reach FARTHER and FASTER and be BIASED toward the direction the player is FACING, so distant NPCs are fully real before you reach them (you should be able to shoot or run over anyone far away): widen the spawn radius + promotion distance and seed more density ahead of the camera facing. In grapple.js (CBZ.body ragdoll, shared by all modes): make the ragdoll SETTLE on top of the ground (no partial sink) and linger consistently with crowd bodies. PRESERVE the promotion system + the crowd combat API (cityCrowdRayHit/Kill/CircleKill) + the CBZ.body{hit,knockdown,fling,busy} signatures (used by jail/survival too). node --check both files.' },

  { key: 'gang-names', files: 'src/city/gangs.js, src/city/careers.js', task:
    'In gangs.js: gang members are named like "RedHook Soldier" / "RedHook OG" — the RANK is jammed into the name and reads dumb. Give each member a REAL First-Last name from the shared name pool (same style as other peds), keep rank as DATA (ped.rank), and show the rank SEPARATELY — as a tag/badge suffix (e.g. "Marcus Vance" with a "· Lt." / "· Soldier" pip on the tag), never as a surname. Also the gangs.js sfx("whoosh") near line 297 -> use a real existing sound or drop it. In careers.js: reword the corny crew/career flavor text (e.g. the "Build a crew" career line) to read sharp, not cheesy. PRESERVE the wave-1 player-gang hooks (cityPlayerGang*, launchWar, bossDead/cityGangMemberDown, cityGangById) + the companion payroll. node --check both.' },

  { key: 'objective', files: 'src/city/story.js', task:
    'In story.js: the objective popup (its own #cityObjective DOM bar) is corny AND overlaps other HUD. (1) Reword the objective lines so they read sharp and not cheesy — especially "Build a crew — recruit 3 soldiers (aim a gun at a ped to recruit)" and the chapter objectives; keep them short + punchy. (2) Fix the bar so it does NOT overlap other on-screen HUD: give it a clean, unobtrusive slot (e.g. a slim line in an empty corner), smaller/subtler styling, and make sure it never covers the radar/money/wanted/ammo. It should be a quiet nudge you can ignore. PRESERVE the chapter/met/reward structure + cityStoryReset. node --check.' },

  { key: 'npc-fire-los', files: 'src/city/combat.js', task:
    'In combat.js: armed NPCs / gang members (npcAttack and any NPC firing path here) must NOT shoot through walls. Before an NPC fires, call CBZ.clearLineOfFire(shooterMuzzle xyz, target xyz) and SKIP the shot when a building blocks it (hold fire / reposition), and hide or lower the gun prop when there is no line of sight so guns stop poking through walls. Keep the melee/fighting feel from the megawave intact (the swing "whoosh" on a melee attack is fine — that is a real swing sound, leave it). PRESERVE all existing combat/melee/npcAttack APIs. node --check.' },

  { key: 'audio', files: 'src/systems/audio.js', task:
    'In systems/audio.js: ADD a REAL "scream" sample to the sfx bank so panicking NPCs have a genuine human scream/yell instead of the DIY "whoosh" (peds.js will call CBZ.sfx("scream")). Source a real, openly-licensed scream/panic/crowd-gasp recording (Wikimedia Commons API or another CC0/PD source via curl), convert it to iOS-safe .m4a with ffmpeg into assets/audio/web/, and wire it into the bank as "scream" matching the existing fx(...) pattern (short, punchy, slightly randomized). Keep volume tasteful. While here, scan the bank for any obviously DIY/placeholder mappings and improve only if clearly broken — do NOT churn working sounds. Confirm the referenced file exists on disk. PRESERVE every existing sfx name + the LOOPS/diegetic siren system. node --check.' },

  { key: 'vehicles', files: 'src/city/vehicles.js, src/city/playercars.js', task:
    'CARJACK realism. In playercars.js: stealing a car currently RE-PAINTS/re-shapes it into a player "style" (cityPromotePlayerCar rebuilds with its own paint, ~line 522/586) — so the car CHANGES COLOR when you steal it. Fix it so a stolen ambient car KEEPS its original color (car.color) and reads as the SAME vehicle you got into (preserve its paint; do not morph an ambient sedan into a supercar on entry). The player-style variety can stay for SPAWNED/owned cars, just not forced onto a freshly jacked one. In vehicles.js: when the player jacks an OCCUPIED car, THROW THE DRIVER OUT (eject as a real ped near the car) and have them REACT on a spectrum: flee, or try to STEAL IT BACK / pull you out, or pull a GUN, or run to call the cops — set the ejected ped intent so the peds-ai brain acts on it (e.g. mark ped.carjackVictim + point its anger at the player). Build on the existing carjack + multi-stage damage code; do NOT undo the asymmetric crash damage. PRESERVE makeCar visuals + userData.body/cabin, runOver/resolveCars/wreckCar/crumpleCar/traffic, the CRASH tune, companion hooks, and cityPromotePlayerCar public signature. node --check both.' },
]

log('Wave 3: ' + DOMAINS.length + ' agents on disjoint files — witness wanted, LOS, aircraft/missiles, reactivity, signs-on-store, doors, bodies, carjack, dumb-text, scream.')

const summaries = await parallel(DOMAINS.map((d) => () =>
  agent(base + '\n\n=== YOUR DOMAIN (' + d.key + ') — edit ONLY: ' + d.files + ' ===\n' + d.task,
    { label: d.key, phase: 'Build' })
    .then((text) => ({ key: d.key, files: d.files, summary: text }))
))

return summaries.filter(Boolean)
