export const meta = {
  name: 'gang-life-megawave',
  description: 'Massive GTA-inspired build: 20 research-first agents deepening every system on disjoint files',
  phases: [{ title: 'Build' }],
}

const ROOT = '/Users/elifoltyn/Downloads/game'
const base = [
  'CELL BLOCK Z / "Gang Life" at ' + ROOT + ': a no-build Three.js r128 browser game, vanilla JS, ~140 IIFE modules on window.CBZ, booted by ordered script tags in index.html. Focus = CITY mode (g.mode==="city"), a GTA-style open world. Per-frame work registers via CBZ.onUpdate(order,fn) (plays-only) or CBZ.onAlways(order,fn); gate with if (CBZ.game.mode!=="city") return;.',
  '',
  'THE MISSION (owner directive): the city currently feels like a GHOST WORLD with dumb pointless AI and a boring economy where nobody gets rich and the rich have nothing to do, lots of half-built ghost code, and weak physics/VFX. Make it COOLER and more REAL, GTA-quality. Be ambitious and thorough — fill in detail, do not leave stubs.',
  '',
  'HARD RULES:',
  '- WEBSEARCH FIRST: every agent MUST do 1-3 WebSearches (e.g. "GTA <your topic>", plus a game-dev technique search) to steal concrete ideas + numbers, THEN implement. Aim for AAA/GTA feel.',
  '- ONLY edit the files assigned to you. index.html and src/config.js are OFF LIMITS (lazy-init: g.x = g.x || ...). Editing another file corrupts a parallel agent.',
  '- LIVE working game: PRESERVE existing behavior and public CBZ functions; extend surgically, do not rewrite whole files. Match code style.',
  '- CRITICAL: after EVERY edit run `node --check <file>` and FIX any error before finishing. Your files MUST parse or you break the whole game. Keep it cheap (this runs on phones): shared geometry/material, time-slicing, distance LOD, pooling.',
  '- End with a 3-4 sentence plain-text summary of what you changed and confirm node --check passed.',
  '',
  'KEY CONTRACTS: CBZ.game(=g){cash,cityBank,respect,wanted,heat,cityKills,cityWeapon,cityInv,cityCrew,playerGang,mode,state}. CBZ.player.pos/.driving/.hp/.maxHp/.stamina/._armor. CBZ.city.note(msg,s)/.big/.addCash/.addRespect/.addKill. CBZ.cityHudDirty(). CBZ.cityPeds[] ped{pos,name,kind,aggr,hp,maxHp,dead,ko,state,target,finalGoal,path,rage,guard,companion,armed,weapon,ammo,archetype,wealth,gang,rank,group,char}. CBZ.cityCops[]. CBZ.cityCars[] car{pos,v,heading,player,npcDriver,group,userData.body,userData.cabin,crumple,wreckT,baseV}. CBZ.cityGangs[]. CBZ.city.arena{shopLots,lots,abandonedLots,homeLots,randomSidewalkPoint(),nearestIntersection(),clampToCity(pos,r),root,spawn}. lot{cx,cz,w,d,kind,building{name,door{x,z,nx,nz},shop,vendor,owned,gang}}. CBZ.cityEcon{ITEMS,SHOP_STOCK,CARS,rollCash,buyPrice,sellPrice,streetPrice,recordSale,propIndex}. CBZ.cityWorldEnsure()/cityEvent(type,data,opts). CBZ.cityCrime(amt,{x,z,type}). CBZ.collide(pos,r,y0,y1). CBZ.colliders/platforms/losBlockers. CBZ.shake(m)/doHitstop(s)/doSlowmo(s). CBZ.gore(x,y,z,{dir,amount,player}). CBZ.body{hit(a,{fromX,fromZ,force,knockdown}),knockdown(a,opts),fling(a,opts),busy(a)} (ragdoll). CBZ.cityExplosion(x,z,{power,radius,byPlayer}). CBZ.tracer(from,to,opts)/muzzleFlash. CBZ.cityShatter(x,z,r)/cityShatterRay(...). CBZ.cityCrowdRayHit/cityCrowdKill (the ambient instanced crowd). CBZ.sfx(name) REAL recorded m4a only (existing: shoot_pistol/smg/carbine/shotgun, punch, hit, ko, headshot, whoosh, step, glass, explosion, coin, siren, win, door); do NOT invent audio names. CBZ.makeLabelSprite(text). Free keybindings only (I/J/K/L/E/F/C/V/M/B/U/G/T/N/O/Tab/Y/Z/H/Q/R/P/X and WASD are TAKEN).',
].join('\n')

const DOMAINS = [
  { key: 'fighting',  files: 'src/city/combat.js', task: 'Make 3rd-person MELEE feel GTA-good: light/heavy attacks, a 3-hit COMBO with timing windows, HIT-STOP on connect (CBZ.doHitstop ~0.05-0.09s), real knockback/stagger/ragdoll on the target (CBZ.body), block/counter for tough NPCs, player stamina drain, and crunchy feedback (shake + sfx punch/hit/ko + brief slow-mo on a KO). Keep existing melee/punch/beat APIs working.' },
  { key: 'shooting',  files: 'src/systems/fpsmode.js, src/systems/gunfx.js', task: 'GTA/AAA GUNPLAY FEEL in fpsmode.js + gunfx.js: a HIT MARKER (crosshair flash on a connecting shot + a kill marker), smoother recoil RECOVERY to center, bloom that tightens standing still / grows moving+auto-firing, and JUICY impacts (sparks/dust/debris via gunfx, blood puff on flesh via CBZ.gore). When a shot hits a wall, call CBZ.cityBulletHole(x,y,z,nx,ny,nz) if it exists (the buildings agent adds it) to leave a hole. PRESERVE: muzzleWorld + weapon userData.muzzle (barrel origin), RK=0.6 recoil dampener, cityCrowdRayHit/Kill, the forward gun pose. Be surgical.' },
  { key: 'vehicles',  files: 'src/city/vehicles.js', task: 'Deepen DRIVING + DAMAGE in vehicles.js. Tune accel/grip/steering for satisfying GTA arcade handling + a handbrake/drift; damage degrades handling. MULTI-STAGE damage: intact -> dented -> SMOKING (emit smoke) -> on FIRE (flames + ticking damage) -> EXPLODE (CBZ.cityExplosion). A car shot/crashed enough catches fire then blows. Build on the existing asymmetric crash damage (do NOT undo it). PRESERVE makeCar + grp.userData.body/cabin, runOver/resolveCars/wreckCar/crumpleCar/traffic, the CRASH tune, companion hooks.' },
  { key: 'exterior',  files: 'src/city/props.js, src/city/world.js', task: 'Real intentional EXTERIOR decoration in props.js (+ world.js for road/sidewalk detail). GTA street furniture that BELONGS: lamp posts (lit emissive head, on at night), fire hydrants, mailboxes, trash cans, bus-stop shelters, BILLBOARDS, planters + low-poly trees, traffic cones, rooftop AC units/vents, A-frame sidewalk shop signs, parking meters, newspaper boxes. NO filler benches. CHEAP (shared geo/mat, distance LOD, hundreds of placements). Big props collide, decor does not; do not block roads/sidewalks.' },
  { key: 'ai',        files: 'src/city/peds.js', task: 'Make NPC AI SMART + ALIVE (not a ghost world) in peds.js. Look-ahead obstacle avoidance + separation (no clumping/clipping; build on the existing stuck-detection), believable threat reactions (flee along CLEAR paths, take cover, scream, call cops at a real distance, crowd panic from gunfire/explosions), daily-life purpose (peds head to jobs/shops/home on loose schedules), and reactions to YOU (stare, film on phone, flee a brandished gun). PRESERVE companionThink (bodyguard/gang brain), stuck-detection, npcAttack, and the aigoals.js goal hooks (coexist; do not override an active fight/flee/companion). Cheap + time-sliced. peds.js is large + central; be careful.' },
  { key: 'economy',   files: 'src/city/economy.js', task: 'Make the ECONOMY FUN, DEEP and REAL in economy.js so a player can get FILTHY RICH and money stays meaningful. Living market: drug/item street prices driven by SUPPLY & DEMAND (dumping floods+drops price; scarcity raises it; recover toward baseline; per-district variance), real buy-low/sell-high loops, heat/risk affecting drug price, and serious money SINKS + high-value faucets so wealth tiers exist (broke -> comfortable -> rich -> kingpin). Research GTA economy + supply/demand pricing. PRESERVE exports ITEMS/SHOP_STOCK/CARS/buyPrice/sellPrice/streetPrice/recordSale/rollCash + the wave-1 property market (propIndex/FINANCE). Drive drift from an onUpdate at a FREE order.' },
  { key: 'buildings', files: 'src/city/buildings.js', task: 'In buildings.js: (1) DEEPEN shop INTERIORS (wave 1 added furnishInterior) with per-business character (bar: stools/neon/bottles/pool table; bank: teller line/vault/ropes; gun store: wall racks/glass cases; gym: weights/mirrors/mats; clothing: racks/mannequins; food: booths/counter/menu; casino: slots/tables), lighting mood, materials. (2) COOLER GLASS breaking (more/realistic shards, spider-crack before full break, sound) — extend cityShatter/burstPane. (3) BULLET HOLES + building damage reactions: expose CBZ.cityBulletHole(x,y,z,nx,ny,nz) that pools a small dark decal quad on the wall (called by the shooting/impact code); scorch marks from explosions; chunks knocked off on big hits. Keep the door->stair aisle clear, colliders sane, cheap (shared geo/mat, pooled decals capped). PRESERVE the window/platform/collider systems + wave-1 furnishInterior.' },
  { key: 'activities',files: 'src/city/activities.js', task: 'Flesh out the GHOST CODE: the [Y] activities board is mostly fake timed stubs. Make the high-value ones actually PLAYABLE or richly simulated with real stakes/odds/payouts and consequences that hit the world: street/legal RACING (a real timed checkpoint race you drive, or a believable simulated one with rivals + betting + payout), CASINO/gambling (blackjack/slots/roulette with real odds + bankroll), BOXING/UFC fight nights (bet + a quick resolved bout with momentum), and a betting sportsbook. Tie payouts/heat/respect into the world (CBZ.city.addCash/addRespect, cityEvent). Research GTA casino/races/fight-night. Keep the existing board structure + CBZ.cityOpenActivities working.' },
  { key: 'wealth',    files: 'src/city/wealth.js', task: 'CREATE the rich/endgame layer in wealth.js (stub exists; overwrite): things for the SUPER-RICH to DO + buy so money matters. Buyable BUSINESSES that generate scaling income (clubs, casinos, dealerships, fronts for laundering dirty money clean), LUXURY money-sinks + status (mansions, yachts, supercars, jewelry, a flashy lifestyle that raises respect/notoriety), a NET-WORTH / wealth-tier system with perks per tier (VIP access, better deals, bodyguard discounts), and high-stakes high-reward opportunities only the rich can access. An IIFE with its own onUpdate (free order) + a small UI/menu on a FREE key or via an existing venue. Research GTA businesses/properties/luxury. Lazy-init g.* state, persist via CBZ.cityWorldEnsure().' },
  { key: 'police',    files: 'src/city/police.js', task: 'GTA-style POLICE escalation in police.js: smarter cops that pursue + flank + use cover, a clear wanted-tier ramp (more + tougher units as stars rise: beat cops -> cruisers -> SWAT -> a helicopter spotlight at high stars), roadblocks/PIT attempts on a driving suspect, give-up/search behavior when you break line of sight, and real arrest flow. Research GTA wanted system. PRESERVE the existing cop spawn/hurt/arrest APIs + the wanted.js integration; coexist with the city wanted-star system.' },
  { key: 'gangs',     files: 'src/city/gangs.js', task: 'Deepen GANG WARS + turf in gangs.js: territory that visibly matters (controlled blocks give income/spawns), dynamic rival-vs-rival wars you can exploit, escalating retaliation when you hit a gang, drive-by attacks, and bigger set-piece turf battles. PRESERVE the wave-1 player-gang hooks (cityPlayerGang*, launchWar skipping the player as attacker, bossDead/cityGangMemberDown, cityGangById) and the existing spawn. Research GTA gang territory/wars.' },
  { key: 'social',    files: 'src/city/social.js', task: 'Make the city feel ALIVE + social in social.js: NPC relationships/partners/families/friend groups, daily routines + crowds gathering (a club at night, a queue at a shop), reactions and gossip spreading, dating/partner depth, and ambient social events. Make it cheap + believable so the streets do not feel like a ghost town. Research GTA pedestrian/ambient life. PRESERVE existing social APIs (cityPartner/cityPropose/cityFlirt/cityIsRomance, witness/tagging).' },
  { key: 'shops',     files: 'src/city/shops.js', task: 'Deepen SHOPPING + businesses in shops.js: richer shop menus per kind with real inventories + prices (clothing that changes your look/respect, barber, electronics, jewelry as wearable flex, food that heals, hardware tools), buying in bulk, haggling, and robbing tills with risk. Make shops feel real, not empty. PRESERVE the existing shop open/close + cityGiveWeapon + the gun-shop stock. Research GTA shops/customization.' },
  { key: 'hud',       files: 'src/city/hud.js', task: 'Polish the CITY HUD/UI in hud.js to feel GTA-clean: a clear money/stat readout, wanted stars, a mini-map/radar with blips (objectives, cops, your gang, shops, your car), ammo + weapon, an objective line, and clean notifications/feed. Make it readable + slick. PRESERVE the existing HUD elements + ENGINE_NAME weapon map + the worldstate summary; extend, do not break layout hooks other systems write to.' },
  { key: 'careers',   files: 'src/city/careers.js', task: 'Deepen JOBS + DRUG DEALING + crime careers in careers.js: a richer job board (delivery, heist, hit, smuggling, getaway-driver, protection rackets), a real drug-dealing loop (buy at the trap house, build a customer base, territory affects sales, busts), and career progression with rising pay/notoriety. PRESERVE the wave-1 companion payroll, cityRecruit auto-enlist into player gang, cityStoryReset chain, and existing job/career APIs. Research GTA missions/jobs/dealing.' },
  { key: 'traffic',   files: 'src/city/traffic.js', task: 'Make city TRAFFIC + density feel like a living GTA city in traffic.js: more believable traffic flow + density that scales with area, varied driver behaviors (cautious/aggressive/reckless), honking + road rage, emergency vehicles responding to incidents (ambulance to bodies, fire truck to fires), and lights that already work — make the whole road system feel alive. PRESERVE the working traffic-light cycle + cityIsRed + red-light enforcement.' },
  { key: 'playercars',files: 'src/city/playercars.js', task: 'Add VEHICLE VARIETY + class in playercars.js: more distinct player car styles (muscle, lowrider, SUV, motorcycle, van) with different handling feel hooks, and if feasible a simple AIRCRAFT (helicopter) or BOAT class for the rich/endgame. Make models read as intentional GTA vehicles. Research GTA vehicle classes. PRESERVE the existing player-car style system + cityPromotePlayerCar/cityCyclePlayerCarStyle hooks.' },
  { key: 'ragdoll',   files: 'src/systems/grapple.js', task: 'Make BODY/RAGDOLL physics REAL in grapple.js (CBZ.body owns hit/knockdown/fling/busy, used by all modes). When a person is shot, hit by a car, or caught in an explosion they should react with believable physics: directional knockback scaled to force, a proper RAGDOLL flop/tumble (limbs/torso), ragdolls that slide + settle on the ground, and bodies that get launched by explosions. Tune the impulse/gravity/settle so it looks like GTA euphoria-lite, not stiff. Research ragdoll physics + GTA euphoria. PRESERVE the CBZ.body API signatures (hit/knockdown/fling/busy) so every caller keeps working across jail/survival/city.' },
  { key: 'explosions',files: 'src/city/crashfx.js', task: 'The EXPLOSIONS currently look RETARDED — overhaul them in crashfx.js (CBZ.cityExplosion + the crash particle system). Make a GTA-quality explosion: a bright expanding fireball (additive sprites, white-hot core -> orange -> deep red), a shockwave ring, a big black smoke plume that rises + lingers, flying debris chunks, sparks/embers, a screen flash + heavy shake + slow-mo, and scorching. It must read as a real explosion, not colored dots. Also make crash impact VFX (sparks, glass, debris) cooler. Research real-time explosion VFX + GTA explosions for concrete params. Keep it pooled + cheap. PRESERVE the cityExplosion(x,z,opts) signature + its blast-damage calls (cityCrowdCircleKill/cityKillPed/cityHurtCop/cityHurtPlayer) + cityCrashFX.' },
  { key: 'gore',      files: 'src/systems/gore.js', task: 'Make GORE/blood feel impactful + real in gore.js (CBZ.gore, shared across modes). Better blood spray directionality (away from the impact), blood pooling/decals under bodies that linger, bigger spray on headshots/explosions, and hit splatter on nearby surfaces. Tasteful but visceral, GTA-level. Keep it cheap (pooled, capped, distance LOD). Research game blood VFX. PRESERVE the CBZ.gore(x,y,z,opts) signature so every caller keeps working.' },
]

const summaries = await parallel(DOMAINS.map((d) => () =>
  agent(base + '\n\nYOUR FILES (own exclusively): ' + d.files + '\n\nTASK: ' + d.task, { label: 'build:' + d.key })
))

const report = {}
DOMAINS.forEach((d, i) => { report[d.key] = summaries[i] || '(no result)' })
return report
