export const meta = {
  name: 'gang-life-wave3-feedback',
  description: 'Round-2 feedback: witness wanted, doors, LOS no-shoot-thru-walls, aircraft missiles+jets+building destruction, NPC reactivity, signs-on-store, body fixes, dumb-text',
  phases: [{ title: 'Build' }],
}

const ROOT = '/Users/elifoltyn/Downloads/game'
const base = [
  'CELL BLOCK Z / "Gang Life" at ' + ROOT + ': no-build Three.js r128, vanilla JS, ~140 IIFE modules on window.CBZ, ordered <script> tags in index.html. CITY mode (g.mode==="city") is a GTA-style open world. Register per-frame work via CBZ.onUpdate(order,fn) (plays-only) / CBZ.onAlways(order,fn); gate with if(CBZ.game.mode!=="city") return;.',
  '',
  'DIRECTIVE (owner): GTA is the REFERENCE not a clone — make content relevant to OUR game. Be ambitious, fill in detail, no stubs.',
  'WEBSEARCH FIRST: do 1-3 quick WebSearches (e.g. "GTA <topic>") for concrete ideas/numbers, then implement.',
  'RULES: ONLY edit your assigned files (index.html + config.js OFF LIMITS; lazy-init g.x=g.x||...). PRESERVE existing public CBZ functions + behavior; extend surgically. After EVERY edit run node --check and FIX errors. Keep it cheap (pooled, time-sliced, LOD). End with a 3-sentence plain-text summary + confirm node --check passed.',
  '',
  'CONTRACTS: CBZ.game(=g){cash,respect,wanted,heat,cityKills,cityWeapon,cityMasked,playerGang,mode}. CBZ.player.pos/.driving/.hp. CBZ.city.note/.big/.addCash/.addRespect/.addKill. CBZ.cityHudDirty(). CBZ.cityPeds[] ped{pos,name,kind,aggr,hp,maxHp,dead,deadT,ko,state,target,finalGoal,path,rage,guard,companion,armed,weapon,ammo,archetype,wealth,gang,rank,snitch,group,char,witnessSev,witnessType,callT,alarmed,fear}. CBZ.cityCops[] cop{pos,swat,dead,armed,sees,npcTarget}. CBZ.cityCars[]. CBZ.cityGangs[]. CBZ.cityGangOf(x,z) (turf at a point). CBZ.city.arena{shopLots,lots,abandonedLots,homeLots,randomSidewalkPoint(),nearestIntersection(),clampToCity(pos,r),root}. lot.building{name,door{x,z,nx,nz},kind}. CBZ.cityEcon. CBZ.cityCrime(amt,{x,z,type}) (current crime entry). CBZ.cityReport(sev,{x,z,type}) (wanted.js: applies stars). CBZ.cityTagWitnesses(x,z,sev,type). CBZ.collide(pos,r,y0,y1) + CBZ.colliders[] (AABB {minX,maxX,minZ,maxZ,...}) + CBZ.losBlockers[] (meshes). CBZ.cityExplosion(x,z,{power,radius,byPlayer}). CBZ.cityShatter(x,z,r). CBZ.cityBulletHole(x,y,z,nx,ny,nz) (buildings.js). CBZ.cityDamageCar/cityCarIgnite (vehicles). CBZ.shake/doHitstop/doSlowmo. CBZ.gore. CBZ.tracer. CBZ.sfx(name) real m4a only (shoot_*, punch,hit,ko,headshot,explosion,siren,glass,coin,win,door); do NOT invent names. Free keys only (I/J/K/L/E/F/C/V/M/B/U/G/T/N/O/Tab/Y/Z/H/Q/R/P/X/WASD all TAKEN).',
].join('\n')

const DOMAINS = [
  { key: 'npc-life', files: 'src/city/peds.js', task: 'In peds.js make EVERY NPC as reactive/alive as a wanted-cop (right now cops are smart, everyone else is a dumb wandering ghost). (1) FULL REACTIVITY SPECTRUM: by personality(aggr/archetype/wealth/gang)+context, a ped can try to KILL you, RUN from you, TRADE/offer you something, STEAL from you/pickpocket, WORK for you (be recruitable), BEAT you up, IGNORE you, or TALK / ask a FAVOR — driven each by a believable trigger, not random. (2) WITNESS REACTION (feeds the new wanted system): when a ped witnesses YOUR crime, it does NOT instantly报警 — based on its p.snitch (roll a per-ped snitch 0..1 at spawn; most low) and the AREA (CBZ.cityGangOf(pos): in gang turf / the hood nobody snitches; rich/clean blocks high; gang members keep omerta, a rival might rat you), it either ignores, or REACTS visibly: pull a phone and CALL (a few sec), RUN toward a cop to report, pull a gun, or flee — and only when that report actually completes does it call CBZ.cityReport(sev,{x,z,type}). Show the tell (CBZ.city.note "📞 ... calling the cops"). (3) SPAWN: peds must generate FARTHER away and AHEAD of the player FACING direction (use CBZ.cam.yaw), faster, so they never pop in near you. (4) Real wall AVOIDANCE (build on stuck-detection so they stop walking into walls). (5) Dead bodies must REST ON the ground (not sink underground — lift the corpse ~0.3 like the player fix) and LINGER longer before despawn. PRESERVE companionThink, npcAttack, aigoals hooks. Time-sliced + cheap.' },
  { key: 'police', files: 'src/city/police.js', task: 'In police.js: (1) LINE OF SIGHT — cops must NOT shoot you through walls (they currently do, guns stick through walls). Before any cop fires, require clear LOS to the target via a segment-vs-collider test against CBZ.colliders/CBZ.losBlockers (write a small raycast helper); if blocked, the cop maneuvers to get an angle instead of firing. (2) GUN STOP — when a beat cop SEES you holding a gun but you are NOT yet wanted, it stops you and challenges you about the weapon (set a flag/state the interact.js agent reads to show EXCUSES / comply / EXECUTE options); back-and-forth with suspicion. (3) AIRCRAFT WEAPONS: at 5 stars the police HELICOPTER fires MISSILES at you (call the new CBZ.cityMissile(fromX,fromY,fromZ, tx,tz) the crashfx agent adds, or CBZ.cityExplosion at the impact with big power) and add FIGHTER JETS that scream in and strafe/missile you at 5 stars. Keep escalation you already built. PRESERVE cop spawn/hurt/arrest APIs + wanted.js integration. node --check.' },
  { key: 'wanted', files: 'src/city/wanted.js', task: 'In wanted.js KILL instant wanted. Right now committing an act (e.g. stealing) can raise stars immediately — remove ALL of that. Stars must ONLY rise when a crime is actually REPORTED TO POLICE by a witness who traveled/called (the peds.js agent calls CBZ.cityReport when a witness completes a report; a cop who directly SEES a violent crime can still radio it in). Make CBZ.cityReport / the report path the SINGLE source of stars; CBZ.cityCrime should only TAG witnesses (CBZ.cityTagWitnesses) + set the current crime, never grant stars by itself. Keep the existing star tiers/heat/decay/labels + cityMasked (disguise) suppression. Coexist with the wave-1 RDR2-style witness scaffolding already here. node --check.' },
  { key: 'buildings-doors', files: 'src/city/buildings.js', task: 'In buildings.js: (1) DOORS — shop/building doors are currently solid invisible WALLS you cannot pass. Make the doorway actually OPEN/passable: leave a real gap in the wall collider at the door (or an openable door mesh that swings/slides when the player is near) so you can WALK THROUGH into the interior. (2) BUILDING DESTRUCTION — expose/extend so buildings take real reactions to explosions/missiles: CBZ.cityDamageBuilding(x,z,radius,power) that knocks chunks off the facade (pooled debris boxes), scorches the wall, shatters nearby glass (CBZ.cityShatter), and on a big hit punches a visible hole/dent — cinematic + cheap. Make sure CBZ.cityBulletHole exists and pools dark decals on walls. (3) Mount store SIGNS ON the building facade (the signage agent owns props.js A-frames; you ensure the building has a proper wall-mounted sign板 over the door). PRESERVE wave-1/2 interiors + window/platform/collider systems + furnishInterior. node --check.' },
  { key: 'signs', files: 'src/city/props.js', task: 'In props.js fix signage + billboards. (1) Freestanding signs standing IN FRONT of stores look dumb — store identification belongs ON THE STORE; reduce/relocate the A-frame sandwich-board sidewalk signs so they sit tight against the storefront (not out in the walkway) and the primary store sign reads as mounted on the building. (2) BILLBOARDS are good but their CONTENT is generic GPT filler — generate RELEVANT in-world content on the billboard ad textures: our city\'s gangs/brands/shops, wanted posters, gang-war taunts, our own jokes, neon club ads — things that belong to THIS game, not generic ads. Keep it cheap (canvas textures, shared/pooled). PRESERVE the rest of the wave-2 street furniture + night-emissive driver. node --check.' },
  { key: 'explosions-missiles', files: 'src/city/crashfx.js', task: 'In crashfx.js: (1) The crash/explosion VFX you built are GOOD — make them LAST LONGER (fireball/smoke/scorch linger longer; tune the lifetimes up). (2) Add a dedicated MISSILE: CBZ.cityMissile(fromX,fromY,fromZ, tx,tz, opts) that flies a visible rocket (with a smoke trail) from a helicopter/jet to a ground target then detonates with a BIGGER and LONGER explosion than a car (a larger fireball, wider shockwave, more debris, bigger scorch) and calls CBZ.cityDamageBuilding(x,z,radius,power) (buildings agent) + the existing blast damage, cinematically. Expose CBZ.cityBigExplosion(x,z,{power}) too. Keep everything pooled + cheap (cap particles). PRESERVE cityExplosion(x,z,opts) signature + its blast-damage calls + cityCrashFX. node --check.' },
  { key: 'gang-names', files: 'src/city/gangs.js, src/city/careers.js', task: 'Fix dumb gang text. In gangs.js: stop naming members "<Gang> Soldier"/"<Gang> OG" — give each gang member a REAL First+Last name (reuse the same name pool civilians use, or a local one), keep ped.rank ("boss"/"lt"/"soldier") for logic, and surface rank as a tag SUFFIX/badge (e.g. the name tag shows the name with a small "· Lt" / a colored rank pip), NOT baked into the name. In careers.js: reword the corny gangster/crew flavor + any "Build a crew" line to something that is not cringe (short, grounded). PRESERVE wave-1/2 gang spawn, player-gang hooks (cityPlayerGang*), notoriety, and existing APIs. node --check both.' },
  { key: 'objective-hud', files: 'src/city/story.js, src/city/hud.js', task: 'Fix the corny, OVERLAPPING objective message (screenshot: "Soldier · Build a crew — recruit 3 soldiers (aim a gun at a ped to recruit)"). In story.js: reword objective/milestone lines to be short + grounded (and the recruit instruction is WRONG — you recruit via the interact menu [K], not by aiming a gun — fix it). In hud.js: ensure the objective/story line has its OWN dedicated, non-overlapping slot in the HUD (it currently collides with other elements) — give it a clean position + max-width + truncation so it never overlaps the job line, feed, money, or stars. PRESERVE the wave-2 HUD layout + cityFeed + radar; just place the objective cleanly. node --check both.' },
  { key: 'cop-interact', files: 'src/city/interact.js', task: 'In interact.js add the COP GUN-STOP interaction: when a cop has stopped you over your visible weapon (the police.js agent sets a flag/state on the cop, e.g. cop.gunStop or g.cityGunStopped), the interact panel for that cop shows GTA-style options: an EXCUSE / talk-your-way-out (e.g. "It\'s licensed" / "Just heading to the range" — success scales with their suspicion + your respect, failure escalates), COMPLY / put it away (holster to defuse), and EXECUTE (shoot the cop — instant heat). Keep it to the 4 IJKL option slots. Also if the recruit option text mentions aiming a gun, fix it (recruit is via this menu). PRESERVE the existing interact panel + hostage/aim menus + the player-gang member options. node --check.' },
]

const summaries = await parallel(DOMAINS.map((d) => () =>
  agent(base + '\n\nYOUR FILES (own exclusively): ' + d.files + '\n\nTASK: ' + d.task, { label: 'build:' + d.key })
))
const report = {}
DOMAINS.forEach((d, i) => { report[d.key] = summaries[i] || '(no result)' })
return report
